# Generated by Django 4.0.2 on 2022-02-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_recruiterprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
        migrations.DeleteModel(
            name='SeekerProfile',
        ),
    ]
