# Generated by Django 4.0.2 on 2022-02-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_recruiterprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerprofile',
            old_name='users',
            new_name='user',
        ),
    ]
