# Generated by Django 4.0.2 on 2022-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_users_seekerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='is_open_to_work',
            field=models.BooleanField(default=True),
        ),
    ]
