# Generated by Django 4.0.2 on 2022-02-12 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_alter_seekerprofile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=300)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('salary', models.BigIntegerField(blank=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('job_role', models.CharField(blank=True, max_length=255)),
                ('valid_till', models.DateField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('organization_logo', models.ImageField(upload_to='recruiter/organization_logo')),
                ('description', models.TextField(blank=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
