# Generated by Django 4.0.2 on 2022-02-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
        migrations.DeleteModel(
            name='SeekerProfile',
        ),
    ]
