# Generated by Django 4.0.2 on 2022-02-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_recruiterprofile_seekerprofile_delete_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
