# Generated by Django 4.0.2 on 2022-02-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_jobposts_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='member_ship',
            new_name='membership',
        ),
    ]
