# Generated by Django 4.0.2 on 2022-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_rename_member_ship_recruiterprofile_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='available_post',
            field=models.SmallIntegerField(default=0),
        ),
    ]
