# Generated by Django 4.0.2 on 2022-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_jobposts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
