# Generated by Django 4.0.2 on 2022-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_jobposts_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposts',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
