# Generated by Django 4.0.2 on 2022-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_jobposts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='job_creation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
