# Generated by Django 4.0.2 on 2022-02-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_jobposts_job_creation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposts',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
