# Generated by Django 4.0.2 on 2022-02-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_alter_jobposts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposts',
            options={'ordering': ('-post_date',)},
        ),
    ]
