# Generated by Django 4.0.2 on 2022-02-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_alter_applicant_job_post_alter_applicant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='board.jobposts'),
        ),
    ]
