# Generated by Django 4.0.2 on 2022-02-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_alter_seekerprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user',
            new_name='user_applied',
        ),
    ]
