# Generated by Django 4.0.2 on 2022-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_rename_user_applicant_user_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='plan_end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='plan_status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='membership',
            field=models.CharField(choices=[('None', 'NONE'), ('Silver', 'Silver'), ('Gold', 'GOLD')], default='None', max_length=10),
        ),
    ]
