# Generated by Django 4.0.2 on 2022-02-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0038_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='recruiter',
        ),
    ]
