# Generated by Django 4.0.2 on 2022-02-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_rename_user_subscription_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='choice_plan_price',
            new_name='choice_plan_price_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='price_gold',
            new_name='price_gold_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='price_silver',
            new_name='price_silver_id',
        ),
    ]
