# Generated by Django 4.0.2 on 2022-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0040_rename_choice_plan_price_subscription_choice_plan_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_gold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_silver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
