# Generated by Django 4.0.2 on 2022-02-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_subscription_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='plan_end_data',
            new_name='plan_end_date',
        ),
    ]
