# Generated by Django 4.0.2 on 2022-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0043_rename_plan_end_data_subscription_plan_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership',
            field=models.CharField(choices=[('None', 'NONE'), ('Silver', 'SILVER'), ('Gold', 'GOLD')], default='None', max_length=10),
        ),
    ]
