# Generated by Django 4.0.2 on 2022-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0046_alter_recruiterprofilemodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='membership',
            field=models.CharField(choices=[('N', 'NONE'), ('S', 'SILVER'), ('G', 'GOLD')], default='N', max_length=6),
        ),
    ]
