# Generated by Django 4.0.2 on 2022-04-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0047_alter_subscriptionplanmodel_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofilemodel',
            name='profile_pic',
        ),
    ]
