# Generated by Django 4.0.2 on 2022-04-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0048_remove_recruiterprofilemodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter/profile_pic'),
        ),
    ]
