# Generated by Django 4.0.2 on 2022-04-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0051_alter_recruiterprofilemodel_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlanModel',
        ),
    ]
