# Generated by Django 4.0.2 on 2022-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0052_delete_subscriptionplanmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofilemodel',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
