# Generated by Django 4.0.2 on 2022-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0053_alter_seekerprofilemodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostsmodel',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
